on:
  workflow_dispatch:
    inputs:
      groupId:
        required: true
        type: string
      artifactId:
        required: true
        type: string
      previousVersion:
        required: true
        type: string
      currentVersion:
        required: true
        type: string
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: sbt/setup-sbt@v1
    - uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
    - run: sbt "runMain mima.App ${{ github.event.inputs.groupId }} ${{ github.event.inputs.artifactId }} ${{ github.event.inputs.previousVersion }} ${{ github.event.inputs.currentVersion }}"
